swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: inventory-api-controller
    description: Inventory Api Controller
paths:
  '/v2/providers/avocado/apis/api/v1/vendors/{vendor}/inventories':
    put:
      tags:
        - inventory-api-controller
      summary: update
      operationId: updateUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
        - name: vendor
          in: path
          description: vendor
          required: true
          type: string
        - in: body
          name: inventories
          description: inventories
          required: true
          schema:
            $ref: '#/definitions/Inventories'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  Inventory:
    type: object
    properties:
      quantity:
        type: integer
        format: int32
    title: Inventory
  Inventories:
    type: object
    properties:
      inventories:
        type: object
        additionalProperties:
          $ref: '#/definitions/Inventory'
    title: Inventories
  Response:
    type: object
    properties:
      success:
        type: boolean
    title: Response